theme: jekyll-theme-minimal
title: Hello, I'm Thomas Wood
logo: /assets/portrait.png
description: A programmer, creative, game developer and Computer Games Technology student aspiring to work in the games industry.
plugins: 
  - jekyll-seo-tag
